rw_platform_home:
    path:     /
    defaults: { _controller: RWPlatformBundle:Advert:index }
    
rw_platform_view:
    path:      /advert/{id}
    defaults: { _controller: RWPlatformBundle:Advert:view }
    
rw_platform_add:
    path:      /add
    defaults: { _controller: RWPlatformBundle:Advert:add }
