rw_platform_home:
    path:      /{page}
    defaults:
        _controller: RWPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*

rw_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: RWPlatformBundle:Advert:view
    requirements:
        id: \d+

rw_platform_add:
    path:      /add
    defaults:
        _controller: RWPlatformBundle:Advert:add

rw_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: RWPlatformBundle:Advert:edit
    requirements:
        id: \d+

rw_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: RWPlatformBundle:Advert:delete
    requirements:
        id: \d+
