test_without_templating:
    path:     /without-templating
    defaults: { _controller: TestBundle:Withouttemplate:index }

test_hello_world:
    path:     /with-templating
    defaults: { _controller: TestBundle:Withtemplate:index }

test_view_slug:
    path:      /test/{year}/{slug}.{format}
    defaults:
        _controller: RWPlatformBundle:Withouttemplate:viewSlug
        format:      html
    requirements:
        year:   \d{4}
        format: html|xml

